jobtype = "opt"
method = "dftb"
verbose = 0
n_cores = 1

[molecule]
charge = 0
multiplicity = 1

[scc]
max_cycles = 250
charge_conv = 1.0e-8
energy_conv = 1.0e-8

[dftb]
gaussian_gamma = false
shell_resolved_gamma = false

[dftb.lc]
enabled = false
radius = 3.03

[dftb.dftb3]
enabled = false
gamma_damping = false
hubbard_derivatives = [-0.1857, -0.1492] # from the element with the lowest atomic number to the highest

[dftb.slater_koster]
use_external_skf = true
skf_directory = "/home/einseler/slater_koster_files/3ob-3-1"

[opt]
state = 1
max_cycles = 500
algorithm = "damped_bfgs"
convergence = "normal"
line_search = true

[excited]
enabled = true
nstates = 10
use_casida = false
get_all_states = false

[excited.davidson]
iterations = 100
convergence = 0.00001
subspace_multiplier = 10

[dispersion]
enabled = false
s6 = 1.0
s8 = 0.01
a1 = 0.497
a2 = 3.622
