jobtype = "initial_conditions"
method = "dftb"
verbose = 0
n_cores = 1

[molecule]
charge = 0
multiplicity = 1

[scc]
max_cycles = 250
charge_conv = 1.0e-8
energy_conv = 1.0e-8

[dftb]
gaussian_gamma = false
shell_resolved_gamma = false

[dftb.lc]
enabled = true
radius = 3.333333

[dftb.slater_koster]
use_external_skf = true
skf_directory = "/home/einseler/slater_koster_files/ob2-1-1/split"

[opt]
state = 0
max_cycles = 500
algorithm = "damped_bfgs"
convergence = "normal"
line_search = true

[dispersion]
enabled = false
s6 = 1.0
s8 = 0.01
a1 = 0.497
a2 = 3.622

[wigner]
n_samples = 10
temperature = 50.0
n_cut = 6
save_in_other_path = false
wigner_path = " "
write_velocities = true
