dynamics_type = "ground_state"
nstep = 100
stepsize = 0.1
restart = false
nstates = 1
coupling = "nacv"

[initial_conditions]
states = [0]
velocities = "boltzmann"
temperature = 300.0

[output]
restart = true
coordinates = true
energies = true
temperature = false
state = false
