[package]
name = "dialect-base"
version = "1.0.0"
authors = [
    "Richard Einsele <richard.einsele@uni-wuerzburg.de>",
    "Joscha Hoche <joscha.hoche@uni-wuerzburg.de>",
    "Roland Mitric <roland.mitric@uni-wuerzburg.de>",
]
edition = "2021"

[dependencies]
ndarray = { version = "0.15.6", features = ["rayon"] }
phf = { version = "0.11.1", features = ["macros"] }
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
